name: Publish Release to Google Play Store

env:
  main_project_module: app
  playstore_name: FitFlow

on:
  push:
    branches:
      - 'release/**'

  workflow_dispatch:

jobs:
  release-build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create keystore.properties from secrets
        env:
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: echo $KEYSTORE_PROPERTIES | base64 -di > ./keystore.properties

      - name: Create Keystore files
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_DEBUG: ${{ secrets.SIGN_KEY_DEBUG }}
        run: |
          echo $SIGN_KEY | base64 -di > ./fitflow-release.jks
          echo $SIGN_KEY_DEBUG | base64 -di > ./fitflow-debug.jks

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

      - name: Bump Version Code
        uses: chkfung/android-version-actions@v1.2.3
        with:
           gradlePath: app/build.gradle.kts
           versionCode: ${{ github.run_number }}
           versionName: 1.0.0

      - name: Build Project
        run: ./gradlew build

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: app/build/outputs/apk/release/

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.github.k409.fitflow
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          track: closed
          status: completed