name: Apply Spotless

on:
  pull_request:
  workflow_dispatch:

jobs:
  spotlessApply:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: set up Java 20
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20

      - name: Apply spotless formatting
        run: ./gradlew spotlessApply

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🤖 Apply Spotless