name: Apply Spotless

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  spotlessApply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: set up Java 20
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create keystore.properties from secrets
        env:
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
        run: echo $KEYSTORE_PROPERTIES | base64 -di > ./keystore.properties

      - name: Create Keystore files
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_DEBUG: ${{ secrets.SIGN_KEY_DEBUG }}
        run: |
          echo $SIGN_KEY | base64 -di > ./fitflow-release.jks
          echo $SIGN_KEY_DEBUG | base64 -di > ./fitflow-debug.jks

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

      - name: Apply spotless formatting
        run: ./gradlew spotlessApply

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🤖 Apply Spotless